package com.bannerbound.antiquity.client.ponder.scenes;

import net.createmod.ponder.api.scene.SceneBuilder;
import net.createmod.ponder.api.scene.SceneBuildingUtil;
import net.minecraft.core.Direction;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.api.distmarker.OnlyIn;

/**
 * Shared helpers for the Bannerbound: Antiquity ponder storyboards.
 * <p>
 * Every station scene animates over the same blank 5×5×5 platform NBT (checkerboard floor at y=0,
 * air above) generated by {@code PonderNbtGen}. Stations are built on top of that floor via
 * {@code scene.world().setBlock(...)} at runtime, so a scene needs no station-specific structure
 * file — only the matching {@code ponder/<sceneName>.nbt} platform copy.
 */
@OnlyIn(Dist.CLIENT)
public final class PonderUtil {
    private PonderUtil() {}

    /** Footprint passed to {@code configureBasePlate} — matches the generated 5-wide platform. */
    public static final int PLATE = 5;
    /** Centre column the single-block / anchor stations sit on. */
    public static final int CX = 2, CZ = 2;
    /** Y of the floor's top face — stations sit on y=1. */
    public static final int CY = 1;

    /** Standard scene opener: 5-wide base plate, gentle zoom, revealed.
     * <p>
     * {@code showBasePlate()} only reveals the y=0 floor layer. These storyboards build their
     * station programmatically with {@code scene.world().setBlock(...)} at y≥1 onto a blank
     * platform NBT — but {@code setBlock} merely redraws <em>already-shown</em> world sections, it
     * never reveals new cells. So we must show the upper layers up front; otherwise every
     * setBlock-placed block lands in a hidden section and renders as nothing (the "no blocks" bug).
     * The cells are air at this point, so revealing them is invisible until a block is placed. */
    public static void basePlate(SceneBuilder scene, SceneBuildingUtil util, float scale) {
        scene.configureBasePlate(0, 0, PLATE);
        scene.scaleSceneView(scale);
        scene.showBasePlate();
        scene.world().showSection(util.select().layersFrom(1), Direction.DOWN);
        scene.idle(5);
    }

    /** Resolve an {@link ItemStack} from a registry id (e.g. {@code "bannerboundantiquity:quicklime"}). */
    public static ItemStack stack(String id) {
        Item item = BuiltInRegistries.ITEM.get(ResourceLocation.parse(id));
        return new ItemStack(item);
    }

    /** Resolve an {@link ItemStack} of {@code count} from a registry id. */
    public static ItemStack stack(String id, int count) {
        ItemStack s = stack(id);
        s.setCount(count);
        return s;
    }

    /** Minimal 1.21.1 ItemStack NBT — id + count, components default to empty. */
    public static CompoundTag itemNbt(String id, int count) {
        CompoundTag t = new CompoundTag();
        t.putString("id", id);
        t.putInt("count", count);
        return t;
    }
}
